/*
 * Java bean class for entity "productos" 
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 21:04:02 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.restaurant.app.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for entity "productos"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Categoria implements Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String nombre;
	
	/**
	 * Default constructor
	 */
	public Categoria() {
		super();
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Override
	public String toString() {
		return nombre;
	}	
}
