/*
 * Created on 2020-07-22 ( Date ISO 2020-07-22 - Time 23:36:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.restaurant.app.model;

import java.io.Serializable;

import java.math.BigDecimal;

/**
 * Java bean for entity "linea_de_venta" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class LineaDeVenta implements Serializable
{
    private static final long serialVersionUID = 1L;
    private Long id ; // Integer // Id or Primary Key
    private Long ventaId ; // Integer // Id or Primary Key

    private BigDecimal precio ;  // BigDecimal 
    private Integer productoId ;  // Integer 

    /**
     * Default constructor
     */
    public LineaDeVenta() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "INT", NotNull : true ) 
     * @param id
     */
	
    /**
     * Set the "ventaId" field value
     * This field is mapped on the database column "venta_id" ( type "INT", NotNull : true ) 
     * @param ventaId
     */
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    public Long getVentaId() {
		return ventaId;
	}

	public void setVentaId(Long ventaId) {
		this.ventaId = ventaId;
	}

	/**
     * Set the "precio" field value
     * This field is mapped on the database column "precio" ( type "DECIMAL", NotNull : true ) 
     * @param precio
     */
    public void setPrecio( BigDecimal precio ) {
        this.precio = precio;
    }
    /**
     * Get the "precio" field value
     * This field is mapped on the database column "precio" ( type "DECIMAL", NotNull : true ) 
     * @return the field value
     */
    public BigDecimal getPrecio() {
        return this.precio;
    }

    /**
     * Set the "productoId" field value
     * This field is mapped on the database column "producto_id" ( type "INT", NotNull : true ) 
     * @param productoId
     */
    public void setProductoId( Integer productoId ) {
        this.productoId = productoId;
    }
    /**
     * Get the "productoId" field value
     * This field is mapped on the database column "producto_id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getProductoId() {
        return this.productoId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(ventaId);
        sb.append("|");
        sb.append(precio);
        sb.append("|");
        sb.append(productoId);
        return sb.toString(); 
    } 



}
