/*
 * Created on 2020-07-22 ( Date ISO 2020-07-22 - Time 23:36:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.restaurant.app.model;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Java bean for entity "venta" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class Venta implements Serializable
{
    private static final long serialVersionUID = 1L;

    public static enum FORMA_PAGO{
        E,
        T
    }

    private Long id ; // Integer // Id or Primary Key


    private Date fecha ;  // Date 

    private BigDecimal importe ;  // BigDecimal 
    private String formaDePago ;  // String 

    private BigDecimal vuelto ;  // BigDecimal
    private List<LineaDeVenta> lineaDeVentaList ;  // BigDecimal
    private boolean pagado;
    private String mesa;
    private BigDecimal disc;


    /**
     * Default constructor
     */
    public Venta() {
        super();
    }
        
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    public Long getId() {
		return id;
	}



	public void setId(Long id) {
		this.id = id;
	}



	/**
     * Set the "fecha" field value
     * This field is mapped on the database column "fecha" ( type "DATETIME", NotNull : false ) 
     * @param fecha
     */
    public void setFecha( Date fecha ) {
        this.fecha = fecha;
    }
    /**
     * Get the "fecha" field value
     * This field is mapped on the database column "fecha" ( type "DATETIME", NotNull : false ) 
     * @return the field value
     */
    public Date getFecha() {
        return this.fecha;
    }

    /**
     * Set the "importe" field value
     * This field is mapped on the database column "importe" ( type "DECIMAL", NotNull : false ) 
     * @param importe
     */
    public void setImporte( BigDecimal importe ) {
        this.importe = importe;
    }
    /**
     * Get the "importe" field value
     * This field is mapped on the database column "importe" ( type "DECIMAL", NotNull : false ) 
     * @return the field value
     */
    public BigDecimal getImporte() {
        return this.importe;
    }

    /**
     * Set the "formaDePago" field value
     * This field is mapped on the database column "forma_de_pago" ( type "VARCHAR", NotNull : false ) 
     * @param formaDePago
     */
    public void setFormaDePago( String formaDePago ) {
        this.formaDePago = formaDePago;
    }
    /**
     * Get the "formaDePago" field value
     * This field is mapped on the database column "forma_de_pago" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getFormaDePago() {
        return this.formaDePago;
    }

    /**
     * Set the "vuelto" field value
     * This field is mapped on the database column "vuelto" ( type "DECIMAL", NotNull : false ) 
     * @param vuelto
     */
    public void setVuelto( BigDecimal vuelto ) {
        this.vuelto = vuelto;
    }
    /**
     * Get the "vuelto" field value
     * This field is mapped on the database column "vuelto" ( type "DECIMAL", NotNull : false ) 
     * @return the field value
     */
    public BigDecimal getVuelto() {
        return this.vuelto;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public List<LineaDeVenta> getLineaDeVentaList() {
        return lineaDeVentaList;
    }

    public void setLineaDeVentaList(List<LineaDeVenta> lineaDeVentaList) {
        this.lineaDeVentaList = lineaDeVentaList;
    }


    public boolean isPagado() {
        return pagado;
    }

    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }

    public String getMesa() {
        return mesa;
    }

    public void setMesa(String mesa) {
        this.mesa = mesa;
    }

    public BigDecimal getDisc() {
        return disc;
    }

    public void setDisc(BigDecimal disc) {
        this.disc = disc;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(importe);
        sb.append("|");
        sb.append(formaDePago);
        sb.append("|");
        sb.append(vuelto);
        return sb.toString(); 
    } 



}
