/*
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 20:59:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.restaurant.app.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;

import com.restaurant.app.model.Productos;
import com.restaurant.app.persistence.ProductosPersistence;
import com.restaurant.app.persistence.impl.jdbc.commons.GenericJdbcDAO;

/**
 * Productos persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("ProductosPersistence")
public class ProductosPersistenceJdbc extends GenericJdbcDAO<Productos> implements ProductosPersistence{

	private final static String SQL_SELECT_ALL = 
		"select id, codigo, nombre, precio, categoria_id from producto"; 

	private final static String SQL_SELECT = 
		"select id, codigo, nombre, precio, categoria_id from producto where id = ?";

	private final static String SQL_INSERT = 
		"insert into producto ( codigo, nombre, precio, categoria_id ) values ( ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update producto set codigo = ?, nombre = ?, precio = ?, categoria_id= ? where id = ?";

	private final static String SQL_DELETE = 
		"delete from producto where id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from producto";

	private final static String SQL_COUNT = 
		"select count(*) from producto where id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public ProductosPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(Productos record, long value) {
		record.setId(value);
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, Productos producto) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, producto.getId() ) ; // "codigo" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, Productos producto) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		// "codigo" is auto-incremented => no set in insert
		setValue(ps, i++, producto.getCodigo() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, producto.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, producto.getPrecio() ) ; // "nombre" : java.lang.String
		
		if(producto.getCategoriaId() != null) {
			setValue(ps, i++, producto.getCategoriaId()) ; // "nombre" : java.lang.String	
		}		
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, Productos producto) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, producto.getCodigo() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, producto.getNombre() ) ; // "nombre" : java.lang.String
		setValue(ps, i++, producto.getPrecio() ) ; // "nombre" : java.lang.String
		if(producto.getCategoriaId() != null) {
			setValue(ps, i++, producto.getCategoriaId()) ; // "nombre" : java.lang.String	
		}	
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, producto.getId() ) ; // "codigo" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param codigo;
	 * @return the new instance
	 */
	private Productos newInstanceWithPrimaryKey( Long id ) {
		Productos producto = new Productos();
		producto.setId( id );
		return producto ;
	}

	//----------------------------------------------------------------------
	@Override
	protected Productos newInstance() {
		return new Productos() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected Productos populateBean(ResultSet rs, Productos producto) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		producto.setId(rs.getLong("id")); // java.lang.Integer
		if ( rs.wasNull() ) { producto.setCodigo(null); }; // not primitive number => keep null value if any
		producto.setCodigo(rs.getString("codigo")); // java.lang.String
		producto.setNombre(rs.getString("nombre")); // java.lang.String
		producto.setPrecio(rs.getDouble("precio")); // java.lang.String
		producto.setCategoriaId(rs.getLong("categoria_id")); // java.lang.String
		if ( rs.wasNull() ) { producto.setCategoriaId(null); };
		return producto ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public Productos findById( Long codigo ) {
		Productos producto = newInstanceWithPrimaryKey( codigo ) ;
		if ( super.doSelect(producto) ) {
			return producto ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	public List<Productos> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param producto
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( Productos producto ) {
		return super.doSelect(producto) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param producto
	 */
	public long insert(Productos producto) {
		Long key = super.doInsertAutoIncr(producto);
		return key.longValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public Productos create(Productos producto) {
		insert(producto);
		return producto ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public boolean update(Productos producto) {
		int r = super.doUpdate(producto);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public Productos save(Productos producto) {
		if ( super.doExists(producto) ) {
			super.doUpdate(producto);
		}
		else {
			producto.setId(super.doInsertAutoIncr(producto));
		}
		return producto ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public boolean deleteById( Long codigo ) {
		Productos producto = newInstanceWithPrimaryKey( codigo ) ;
		int r = super.doDelete(producto);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	
	public boolean delete( Productos producto ) {
		int r = super.doDelete(producto);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param codigo;
	 * @return
	 */
	// @Override
	public boolean exists( Long codigo ) {
		Productos producto = newInstanceWithPrimaryKey( codigo ) ;
		return super.doExists(producto);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param producto
	 * @return
	 */
	// @Override
	public boolean exists( Productos producto ) {
		return super.doExists(producto);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
