/*
 * Created on 2019-06-27 ( Date ISO 2019-06-27 - Time 20:59:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.restaurant.app.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * 
 * @author Telosys
 *
 */
public class PersistenceJdbcServicePattern {

	public final static String  PATTERN = "%s.impl.jdbc.%sJdbc" ;
	
}
